sudo: false
language: erlang
install: 'true'
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- chmod +x rebar3
env: PATH=$PATH:.
cache:
  directories:
  - $HOME/.cache/rebar3/
otp_release:
- 21.0.2  
- 20.3
- 19.3
- 18.1
script: "./bin/checks.sh && rebar3 as test coveralls send"
